// Movies action types
export const GET_UPCOMMING_MOVIES = 'GET_UPCOMMING_MOVIES';
export const GET_UPCOMMING_MOVIES_ERROR = 'GET_UPCOMMING_MOVIES_ERROR';

export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const GET_TOP_RATED_MOVIES_ERROR = 'GET_TOP_RATED_MOVIES_ERROR';

export const GET_LATEST_MOVIE = 'GET_LATEST_MOVIE';
export const GET_LATEST_MOVIE_ERROR = 'GET_LATEST_MOVIE_ERROR';

export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_POPULAR_MOVIES_ERROR = 'GET_POPULAR_MOVIES_ERROR';

export const GET_NETFLIX_ORIGINALS = 'GET_NETFLIX_ORIGINALS';
export const GET_NETFLIX_ORIGINALS_ERROR = 'GET_NETFLIX_ORIGINALS_ERROR';

